language: r
sudo: false
script: make hw2sol
cache: packages
r_packages:
  - rmarkdown
  - neotoma
  - purrr
  - ggplot2
  - plyr
  - reshape2
  - mgcv
  - Bchron
  - viridis
  - dplyr
  - readr
  - gridExtra
  - knitr
  - Rcpp
os:
  - linux
  - osx
r:
  - 3.5.2
  - 2
