language: r
sudo: false
script: make hw2sol
cache: packages
r_packages:
  - rmarkdown
  - knitr
  - Rcpp
  - shiny
  - readr
  - dplyr
  - tidyverse
  - ggplot2
os:
  - linux
  - osx
r:
  - oldrel
  - release
